package email

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// Config holds SendGrid configuration
type Config struct {
	APIKey    string
	FromEmail string
	FromName  string
}

// Service handles email sending via SendGrid
type Service struct {
	config *Config
	client *http.Client
}

// New creates a new SendGrid email service
func New(config *Config) *Service {
	return &Service{
		config: config,
		client: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// Email represents an email message
type Email struct {
	To      string
	ToName  string
	Subject string
	Body    string
	HTML    string // If provided, sends as HTML
}

// SendEmail sends an email
func (s *Service) SendEmail(email *Email) error {
	if s.config.APIKey == "" {
		return fmt.Errorf("SendGrid API key not configured")
	}

	fromName := s.config.FromName
	if fromName == "" {
		fromName = "DukaPOS"
	}

	msg := map[string]interface{}{
		"personalizations": []map[string]interface{}{
			{
				"to": []map[string]string{
					{
						"email": email.To,
						"name":  email.ToName,
					},
				},
			},
		},
		"from": map[string]string{
			"email": s.config.FromEmail,
			"name":  fromName,
		},
		"subject": email.Subject,
	}

	if email.HTML != "" {
		msg["content"] = []map[string]string{
			{"type": "text/html", "value": email.HTML},
			{"type": "text/plain", "value": email.Body},
		}
	} else {
		msg["content"] = []map[string]string{
			{"type": "text/plain", "value": email.Body},
		}
	}

	jsonData, err := json.Marshal(msg)
	if err != nil {
		return err
	}

	req, err := http.NewRequest("POST", "https://api.sendgrid.com/v3/mail/send", bytes.NewBuffer(jsonData))
	if err != nil {
		return err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+s.config.APIKey)

	resp, err := s.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	if resp.StatusCode >= 400 {
		return fmt.Errorf("email send failed (status %d): %s", resp.StatusCode, string(body))
	}

	return nil
}

// SendReportEmail sends a report email
func (s *Service) SendReportEmail(to, shopName string, reportData map[string]interface{}) error {
	html := fmt.Sprintf(`
		<html>
		<body style="font-family: Arial, sans-serif; padding: 20px;">
			<h2 style="color: #2ecc71;">📊 %s - Daily Report</h2>
			<table style="width: 100%%; border-collapse: collapse;">
				<tr>
					<td style="padding: 10px; border: 1px solid #ddd;"><strong>Total Sales</strong></td>
					<td style="padding: 10px; border: 1px solid #ddd;">KSh %.0f</td>
				</tr>
				<tr>
					<td style="padding: 10px; border: 1px solid #ddd;"><strong>Transactions</strong></td>
					<td style="padding: 10px; border: 1px solid #ddd;">%d</td>
				</tr>
				<tr>
					<td style="padding: 10px; border: 1px solid #ddd;"><strong>Profit</strong></td>
					<td style="padding: 10px; border: 1px solid #ddd;">KSh %.0f</td>
				</tr>
			</table>
			<p style="color: #666; margin-top: 20px;">
				Generated by DukaPOS - WhatsApp POS for Kenyan Businesses
			</p>
		</body>
		</html>
	`, shopName,
		reportData["total_sales"],
		reportData["transactions"],
		reportData["profit"],
	)

	email := &Email{
		To:      to,
		ToName:  shopName,
		Subject: fmt.Sprintf("%s - Daily Report", shopName),
		Body: fmt.Sprintf(`
%s - Daily Report

Total Sales: KSh %.0f
Transactions: %d
Profit: KSh %.0f

Generated by DukaPOS
		`, shopName,
			reportData["total_sales"],
			reportData["transactions"],
			reportData["profit"],
		),
		HTML: html,
	}

	return s.SendEmail(email)
}

// SendWelcomeEmail sends a welcome email to new shops
func (s *Service) SendWelcomeEmail(to, shopName string) error {
	html := fmt.Sprintf(`
		<html>
		<body style="font-family: Arial, sans-serif; padding: 20px;">
			<h2 style="color: #2ecc71;">🎉 Welcome to DukaPOS!</h2>
			<p>Hi %s,</p>
			<p>Thank you for joining DukaPOS - WhatsApp POS for Kenyan Businesses!</p>
			<h3>Quick Start:</h3>
			<ol>
				<li>Save our WhatsApp number</li>
				<li>Send: <code>add [product] [price] [qty]</code> to add products</li>
				<li>Send: <code>sell [product] [qty]</code> to record sales</li>
				<li>Send: <code>report</code> to see daily summary</li>
			</ol>
			<p>Need help? Reply to this email or contact support.</p>
			<p style="color: #666;">
				Best regards,<br>
				The DukaPOS Team
			</p>
		</body>
		</html>
	`, shopName)

	email := &Email{
		To:      to,
		ToName:  shopName,
		Subject: "Welcome to DukaPOS!",
		Body: fmt.Sprintf(`
Welcome to DukaPOS!

Hi %s,

Thank you for joining DukaPOS - WhatsApp POS for Kenyan Businesses!

Quick Start:
1. Save our WhatsApp number
2. Send: add [product] [price] [qty] to add products
3. Send: sell [product] [qty] to record sales
4. Send: report to see daily summary

Need help? Contact support.

Best regards,
The DukaPOS Team
		`, shopName),
		HTML: html,
	}

	return s.SendEmail(email)
}
